### ISSUE TITLE
TaskManager ignores providedOptions

### ISSUE THREAD

**Issue by dani-sandu** [conductor-sdk/conductor-javascript#22]
Hello ,
I noticed that the options provided to the TaskManager are ignored ( pollInterval, domain, concurrency) , only workerId is being used . 
So I assumed after the defaultManagerOption spread should be another spread with providedOptions.

```
    const providedOptions = config.options ?? {}
    this.taskManageOptions = {
      ...defaultManagerOptions,
      ...providedOptions,
      workerID: workerId(providedOptions),
    }
```
https://github.com/conductor-sdk/conductor-javascript/blob/570dddaf4c62d414c836664801e8c51dff579f25/src/task/TaskManager.ts#L45-L49

**Comment by gardusig** [comment]
Thanks for the feedback @dani-sandu! We'll look into that and publish a new release soon :)
