### ISSUE TITLE
Unable to specify https agent options

### ISSUE THREAD

**Issue by daviesjamie** [conductor-sdk/conductor-javascript#26]
In the README for the project, one example shows that a custom `https.Agent` can be passed in using the `AGENT` key in the client options:

```ts
const client = new ConductorClient({
  serverUrl: 'https://play.orkes.io/api',
  AGENT: new Agent(agentOptions)
})
```

When attempting to do this, we're seeing an error about the `AGENT` key not being a valid option:

```
Argument of type '{ serverUrl: string; AGENT: https.Agent; }' is not assignable to parameter of type 'Partial<ConductorClientAPIConfig>'.
  Object literal may only specify known properties, and 'AGENT' does not exist in type 'Partial<ConductorClientAPIConfig>'.ts(2345)
```

Having looked at the source code, it doesn't seem like there is a way of specifying a custom agent?

We're using a self-signed SSL certificate on a local version of Conductor for development purposes, and this issue means that we cannot use this library to connect.

Are we missing anything?

**Comment by gardusig** [comment]
Hi @daviesjamie! Sorry, I think docs and codebase got a few updates recently. `ConductorClient` constructor must receive a `requestHandler` parameter to override it ([reference](https://github.com/conductor-sdk/conductor-javascript/blob/f65d08a42b00b562f367097ec9fd6270e1174b98/src/common/open-api/ConductorClient.ts#L46)).

By sending a custom function as the `request` at `ConductorHttpRequest` ([reference](https://github.com/conductor-sdk/conductor-javascript/blob/92dbb13ffaac21c8a4bc67a149cc3b8216987cee/src/common/RequestCustomizer.ts#L26)), the code could potentially be placed before [this](https://github.com/conductor-sdk/conductor-javascript/blob/aafe4462012a72715b02dd85d5f8d6a54ec4dbfe/src/common/open-api/core/request.ts#L305) and its done :)
