### ISSUE TITLE
ERROR Error polling for tasks: Headers is not defined ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by Yashg2910** [conductor-sdk/conductor-javascript#53]
### Discussed in https://github.com/conductor-sdk/conductor-javascript/discussions/52

<div type='discussions-op-text'>

<sup>Originally posted by **Yashg2910** December 15, 2023</sup>
Hi, I am getting the following error when I try to poll conductor using the npm library node v.16.14.2.
Can someone tell me what am I missing?

` ERROR Error polling for tasks: Headers is not defined ReferenceError: Headers is not defined
     at getHeaders2 (/usr/src/app/node_modules/@io-orkes/conductor-javascript/dist/index.js:3751:3)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async /usr/src/app/node_modules/@io-orkes/conductor-javascript/dist/index.js:3828:23`</div>

**Comment by Sudakatux** [comment]
This will only work with node18 or older
